// Code generated by protoc-gen-zig
///! package disk_usage
const std = @import("std");

const protobuf = @import("protobuf");
const fd = protobuf.fd;
/// import package rustproto
const rustproto = @import("rustproto.pb.zig");

pub const DiskUsage = enum(i32) {
    Normal = 0,
    AlmostFull = 1,
    AlreadyFull = 2,
    _,
};
