// Code generated by protoc-gen-zig
///! package gogoproto
const std = @import("std");

const protobuf = @import("protobuf");
const fd = protobuf.fd;
/// import package google.protobuf
const google_protobuf = @import("google/protobuf.pb.zig");
